# Generated by Django 5.1.4 on 2024-12-10 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictation',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dictations', to='dictation.lesson'),
            preserve_default=False,
        ),
    ]
